---
- name: joaocosta.dev zulip host (ifgsv) Ansible playbook
  hosts: joaocostadev_zulip

  tasks:
    - name: Copy zulip.conf
      ansible.builtin.copy:
        src: zulip.conf
        dest: /etc/zulip/zulip.conf
        owner: zulip
        group: zulip
        mode: "0644"
      notify: Puppet apply

    - name: Copy settings.py
      ansible.builtin.template:
        src: settings.py.j2
        dest: /etc/zulip/settings.py
        owner: zulip
        group: zulip
        mode: "0644"
      notify: Restart zulip server

  handlers:
    - name: Puppet apply
      become: true
      ansible.builtin.command:
        cmd: /home/zulip/deployments/current/scripts/zulip-puppet-apply
      listen: "Apply special settings"

    - name: Restart zulip server
      ansible.builtin.command:
        cmd: /home/zulip/deployments/current/scripts/restart-server
      listen: "Restart zulip server"
