services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    userns_mode: "host"
    expose:
      - "2283"
    environment:
      TZ: ${TZ}
    env_file:
      - /usr/local/etc/immich.env
    volumes:
      - type: volume
        source: immich-nas
        target: /usr/src/app/upload
        volume:
          nocopy: true
      # - immich-thumbs:/usr/src/app/upload/thumbs
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    environment:
      TZ: ${TZ}
    env_file:
      - /usr/local/etc/immich.env
    volumes:
      - model-cache:/cache
    restart: always
    healthcheck:
      disable: false

volumes:
  model-cache:
  immich-nas:
    external: true
  # immich-thumbs:
