services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.133.1
    userns_mode: "host"
    volumes:
      - type: volume
        source: immich-nas
        target: /usr/src/app/upload
        volume:
          nocopy: true
      # - immich-thumbs:/usr/src/app/upload/thumbs
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - /usr/local/etc/immich.env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.133.1
    volumes:
      - model-cache:/cache
    env_file:
      - /usr/local/etc/immich.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: postgres
    image: ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.2.1
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    env_file:
      - /usr/local/etc/immich.env
    volumes:
      - immich-db:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
  immich-db:
  immich-nas:
    external: true
  # immich-thumbs:
