name: site

services:
  caddy:
    image: ghcr.io/joaocostaifg/caddy:master
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      TZ: ${TZ}
    env_file: /usr/local/etc/caddy.env
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - /run/tailscale/tailscaled.sock:/run/tailscale/tailscaled.sock
    restart: unless-stopped
  # ---
  website:
    image: ghcr.io/joaocostaifg/website:master
    container_name: website
    expose:
      - "3000"
    environment:
      TZ: ${TZ}
    restart: unless-stopped
  # ---
  vaultwarden:
    image: vaultwarden/server:1.33.2
    container_name: vaultwarden
    expose:
      - "80"
      - "3012"
    environment:
      TZ: ${TZ}
      WEBSOCKET_ENABLED: true
      EXPERIMENTAL_CLIENT_FEATURE_FLAGS: ssh-key-vault-item,ssh-agent
    volumes:
      - site_bw_data:/data
    restart: unless-stopped
  # ---
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    expose:
      - "80"
    environment:
      TZ: ${TZ}
      PUID: 1000
      PGID: 1000
    volumes:
      - site_heimdall_data:/config
    restart: unless-stopped
  # ---
  minecraft:
    image: itzg/minecraft-server:java21-graalvm
    container_name: minecraft
    ports:
      - "25565:25565"
    environment:
      TZ: ${TZ}
      EULA: TRUE
      TYPE: PURPUR
      VERSION: 1.19.4
      MEMORY: 6G
      MAX_MEMORY: 10G
      USE_AIKAR_FLAGS: TRUE
      USE_SIMD_FLAGS: TRUE
    volumes:
      - site_mine_data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
  # ---
  pingvin-share:
    image: stonith404/pingvin-share
    container_name: pingvin
    expose:
      - "3000"
    environment:
      TZ: ${TZ}
    volumes:
      - site_pingvin_data:/opt/app/backend/data
      - site_pingvin_imgs:/opt/app/frontend/public/img
    restart: unless-stopped
  # ---
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: pdf
    expose:
      - "8080"
    environment:
      TZ: ${TZ}
      DOCKER_ENABLE_SECURITY: false
    volumes:
      - site_pdf_trainingdata:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - site_pdf_config:/configs
    restart: unless-stopped
  # ---
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    expose:
      - "8080"
    userns_mode: "host"
    environment:
      TZ: ${TZ}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
  # ---
  joplin:
    image: joplin/server:latest
    container_name: joplin
    expose:
      - "22300"
    environment:
      TZ: ${TZ}
      APP_BASE_URL: https://joplin.tail1dfda.ts.net
      APP_PORT: 22300
      SQLITE_DATABASE: /data/db.sqlite
    volumes:
      - joplin_data:/data
    restart: unless-stopped
  # ---
  rss2email:
    image: ghcr.io/skx/rss2email:master
    container_name: rss2email
    working_dir: /app
    entrypoint: rss2email
    command: daemon -verbose rss@joaocosta.dev
    environment:
      TZ: ${TZ}
    env_file: /usr/local/etc/rss2email.env
    volumes:
      - rss2email-data:/app/.rss2email
    restart: unless-stopped
  # ---
  open-webui:
    image: ghcr.io/open-webui/open-webui:dev
    container_name: open-webui
    expose:
      - "8080"
    environment:
      TZ: ${TZ}
    volumes:
      - open-webui_data:/app/backend/data
    restart: unless-stopped
  # ---
  database:
    image: ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.2.1
    container_name: postgres
    environment:
      TZ: ${TZ}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    env_file:
      - /usr/local/etc/postgres.env
    volumes:
      - immich-db:/var/lib/postgresql/data
    restart: always
  # ---
  redis:
    image: docker.io/redis:8-alpine
    container_name: redis
    expose:
      - "6379"
    environment:
      TZ: ${TZ}
    volumes:
      - redisdata:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
  # ---
  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    environment:
      TZ: ${TZ}
    volumes:
      - traccar_data:/opt/traccar/data
      - ./traccar.xml:/opt/traccar/conf/traccar.xml:ro
    expose:
      - "8082"
    restart: unless-stopped
  # ---
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    environment:
      TZ: ${TZ}
    volumes:
      - ./searxng:/etc/searxng:rw
    expose:
      - "8080"
    restart: unless-stopped

volumes:
  site_bw_data:
  site_heimdall_data:
  site_mine_data:
  site_pingvin_data:
  site_pingvin_imgs:
  site_pdf_trainingdata:
  site_pdf_config:
  joplin_data:
  rss2email-data:
  open-webui_data:
  caddy_data:
  caddy_config:
  redisdata:
  immich-db:
  traccar_data:
