root_route:
    path:     /
    controller: Controllers\HomeController::show

home_route:
    path:     /home
    controller: Controllers\HomeController::show
 
foo_placeholder_route:
    path:     /foo/{id}
    controller: Controllers\HomeController::show
    requirements:
        id: '[0-9]+'
