foo_route:
    path:     /foo
    controller: controllers\HomeController::show
 
foo_placeholder_route:
    path:     /foo/{id}
    controller: controllers\HomeController::show
    requirements:
        id: '[0-9]+'
