root_route:
    path:       /
    controller: Controllers\HomeController::redirect
home_route:
    path:       /home
    controller: Controllers\HomeController::show
about_route:
    path:       /about
    controller: Controllers\AboutController::show
contacts_route:
    path:       /contacts
    controller: Controllers\ContactsController::show
projects_route:
    path:       /projects
    controller: Controllers\ProjectsController::show

blog_index_route:
    path:       /blog
    controller: Controllers\BlogController::showIndex
blog_post_route:
    path:       /blog/{id}
    controller: Controllers\BlogController::showPost
    requirements:
        id: '[0-9]+'
blog_insert_route:
    path:       /new_blog
    controller: Controllers\BlogController::showNewPostForm
blog_insert_action:
    path:       /new_blog_action
    controller: Controllers\BlogController::newPost
    methods:    POST
blog_edit_route:
    path:       /edit_blog/{id}
    controller: Controllers\BlogController::showEditPostForm
    requirements:
        id: '[0-9]+'
blog_edit_action:
    path:       /edit_blog_action
    controller: Controllers\BlogController::editPost
    methods:    POST

user_login_route:
    path:       /login
    controller: Controllers\UserController::showLoginForm
user_login_action:
    path:       /login_action
    controller: Controllers\UserController::login
    methods:    POST
user_logout_route:
    path:       /logout
    controller: Controllers\UserController::logout

fallback_route:
    path:     /404
    controller: Controllers\FallbackController::show
