---
- name: Install apcupsd
  ansible.builtin.apt:
    name:
      - apcupsd
    state: present
- name: Config apcupsd
  copy:
    src: apcupsd.conf
    dest: /etc/apcupsd/apcupsd.conf
    owner: root
    group: root
- name: Enable apcupsd service
  systemd:
    name: apcupsd
    enabled: yes
    masked: no
