---
- name: Install msmtp and msmtp-mta
  community.general.pacman:
    name:
      - msmtp
      - msmtp-mta
    state: present
- name: Update crontab config to send mails - MAILTO
  ansible.builtin.cron:
    name: MAILTO
    env: yes
    job: joaocosta@posteo.net
- name: Update crontab config to send mails - MAILFROM
  ansible.builtin.cron:
    name: MAILFROM
    env: yes
    job: euviumsapo.umgrande@sapo.pt
