---
- name: Add tailscale repo keys
  ansible.builtin.command:
    cmd: curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg >/usr/share/keyrings/tailscale-archive-keyring.gpg
    creates: /usr/share/keyrings/tailscale-archive-keyring.gpg
- name: Add tailscale repo list
  ansible.builtin.command:
    cmd: curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list >/etc/apt/sources.list.d/tailscale.list
    creates: /etc/apt/sources.list.d/tailscale.list
- name: Install tailscale
  ansible.builtin.apt:
    name:
      - tailscale
    state: present
- name: Add tailscale serve service
  copy:
    src: tailscale_serve.service
    dest: /etc/systemd/system/tailscale_serve.service
    owner: root
    group: root
- name: Enable tailscale_serve service
  systemd:
    name: tailscale_serve
    enabled: yes
    masked: no
    daemon_reload: true
