services:
  php:
    build:
      target: php_dev
    volumes:
      - ./src:/app/main
      - ./wiki:/app/wiki
      - ./data/main:/data/main
  nginx:
    build:
      target: nginx_dev
    volumes:
      - ./src:/app/main
      - ./wiki:/app/wiki
      - ./data/main:/data/main

secrets:
  joaocosta.dev:
    file: ./nginx/keys
  joaocosta.dev_ecc:
    file: ./nginx/keys
