services:
  php:
    build:
      target: php_dev
    volumes:
      - ./src:/app/main
      - ./wiki:/app/wiki
      - ./data/database:/data/database
      - ./data/storage:/data/storage
  nginx:
    build:
      target: nginx_dev
    volumes:
      - ./src:/app/main
      - ./wiki:/app/wiki
      - ./data/database:/data/database
      - ./data/storage:/data/storage

secrets:
  joaocosta.dev:
    file: ./nginx/keys
  joaocosta.dev_ecc:
    file: ./nginx/keys
