services:
  php:
    build:
      target: php_dev
    volumes:
      - ./src:/app/main
      - ./src/data/database:/app/main/database
      - ./src/data/storage:/app/main/storage
      - ./wiki:/app/wiki
  nginx:
    build:
      target: nginx_dev
    volumes:
      - ./src:/app/main
      - ./src/data/database:/app/main/database
      - ./src/data/storage:/app/main/storage
      - ./wiki:/app/wiki
      - /run/tailscale.nginx-auth.sock:/run/tailscale.nginx-auth.sock

secrets:
  joaocosta.dev:
    file: ./nginx/keys
  joaocosta.dev_ecc:
    file: ./nginx/keys
