services:
  php:
    build:
      target: php_dev
    volumes:
      - ./src:/app/main
      - ./wiki:/app/wiki
      - ./data/database/:/data/database/
      # - ./src/data/storage:/app/main/storage
  nginx:
    build:
      target: nginx_dev
    volumes:
      - ./src:/app/main
      - ./wiki:/app/wiki
      - ./data/database/:/data/database/
      # - ./src/data/storage:/app/main/storage

secrets:
  joaocosta.dev:
    file: ./nginx/keys
  joaocosta.dev_ecc:
    file: ./nginx/keys
