version: "3.9"

services:
  php:
    build:
      target: php_dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/app/main
      - ./wiki:/app/wiki
      - ./data/main:/data/main
