services:
  php:
    build:
      target: php_test
    volumes:
      - ./src:/app/main
      - ./src/data/database:/app/main/database
      - ./src/data/storage:/app/main/storage
      - ./wiki:/app/wiki
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.dev
    volumes:
      - ./src:/app/main
      - ./src/data/database:/app/main/database
      - ./src/data/storage:/app/main/storage
      - ./wiki:/app/wiki

secrets:
  joaocosta.dev:
    file: ./nginx/keys
  joaocosta.dev_ecc:
    file: ./nginx/keys
