version: "3.8"

services:
  tor:
    build: ./tor
    container_name: tor
    volumes:
      - tor_socket:/socket
  php:
    build: ./php
    container_name: php
    volumes:
      - php_socket:/socket
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - php_socket:/php-socket
      - tor_socket:/tor-socket

volumes:
  php_socket:
  tor_socket:
