version: "3.8"

services:
  tor:
    build: ./tor
    container_name: tor
    volumes:
      - tor_socket:/socket
  php:
    build: ./php
    container_name: php
    volumes:
      - php_socket:/socket
      - ./nginx/src:/main
      - ./nginx/wiki:/wiki
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - php_socket:/php-socket
      - tor_socket:/tor-socket
      - ./nginx/src:/main
      - ./nginx/wiki:/wiki
      - ./nginx/keys/server.crt:/etc/letsencrypt/joaocosta.dev/fullchain.cer:ro
      - ./nginx/keys/server.key:/etc/letsencrypt/joaocosta.dev/joaocosta.dev.key:ro
      - ./nginx/keys/server.crt:/etc/letsencrypt/joaocosta.dev_ecc/fullchain.cer:ro
      - ./nginx/keys/server.key:/etc/letsencrypt/joaocosta.dev_ecc/joaocosta.dev.key:ro

volumes:
  php_socket:
  tor_socket:
