version: "3.9"

services:
  tor:
    build: ./tor
    container_name: tor
    volumes:
      - tor_socket:/socket
    restart: unless-stopped
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php
    networks:
      - php_internal
    restart: unless-stopped
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - php_internal
      - languagetool_internal
    volumes:
      - tor_socket:/socket
    secrets:
      - joaocosta.dev
      - joaocosta.dev_ecc
    depends_on:
      - tor
      - php
    restart: unless-stopped
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    networks:
      - languagetool_internal
    environment:
        - Java_Xms=256m  # minimum Java heap size of 256 mib
        - Java_Xmx=1g  # maximum Java heap size of 1 Gib

networks:
  php_internal:
    driver: bridge
  languagetool_internal:
    driver: bridge

volumes:
  tor_socket:
