version: "3"

services:
  tor:
    build: ./tor
    container_name: tor
    volumes:
      - tor_socket:/socket
    restart: no
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php
    networks:
      - php_internal
    restart: unless-stopped
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - tor_socket:/tor-socket
    networks:
      - php_internal
    restart: unless-stopped

networks:
  php_internal:
    driver: bridge

volumes:
  php_socket:
  tor_socket:
