version: "3.8"

services:
  tor:
    build: ./tor
    container_name: tor
    volumes:
      - tor_socket:/socket
    restart: unless-stopped
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php
    volumes:
      - php_socket:/socket
    restart: unless-stopped
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - php_socket:/php-socket
      - tor_socket:/tor-socket
    restart: unless-stopped

volumes:
  php_socket:
  tor_socket:
