services:
  synapse:
    build:
      context: ./matrix/synapse
    container_name: synapse
    ports:
      - "8070:8008"
    volumes:
      - site_synapse_data:/data
    restart: unless-stopped
  coturn:
    image: instrumentisto/coturn:latest
    container_name: coturn
    userns_mode: 'host'
    network_mode: host
    environment:
      - DETECT_EXTERNAL_IP=yes
      - DETECT_RELAY_IP=yes
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
    # to speedup coturn, the data retention is mapped to a tmpfs
    tmpfs:
      - /var/lib/coturn
    secrets:
      - coturn_conf
    command: ["--log-file=stdout", "--external-ip=$(detect-external-ip)", "-c /run/secrets/coturn_conf"]
    restart: unless-stopped
  synapse-admin:
    image: awesometechnologies/synapse-admin:latest
    container_name: synapse-admin
    volumes:
      - ./matrix/synapse_admin.json:/app/config.json:ro
    ports:
      - "8071:80"
    restart: unless-stopped
  element:
    image: vectorim/element-web:latest
    container_name: element
    volumes:
      - ./matrix/element-web.json:/app/config.json:ro
    ports:
      - "8072:80"
    restart: unless-stopped

volumes:
  site_synapse_data:

secrets:
  coturn_conf:
    file: /usr/local/etc/turnserver.conf
