services:
  tor:
    volumes:
      - /var/log:/var/log
      - tor_data:/var/lib/tor/joaocosta.dev
  php:
    volumes:
      - /var/log:/var/log
      - app_code:/app
      - site_app_data:/data
  nginx:
    volumes:
      - /var/log:/var/log
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - app_code:/app
      - site_app_data:/data

volumes:
  app_code:
  site_app_data:
    external: true
  tor_data:
