version: "3.9"

services:
  php:
    build:
      target: php_prod
    volumes:
      - site_app_data:/data
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    environment:
      - langtool_languageModel=/ngrams
      - Java_Xms=256m  # minimum Java heap size of 256 mib
      - Java_Xmx=1g  # maximum Java heap size of 1 Gib
    ports:
      - "8010:8010"
    volumes:
      - /usr/local/lib/ngrams:/ngrams
    restart: unless-stopped
  vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    environment:
      - WEBSOCKET_ENABLED=true
    ports:
      - "8020:80"
    volumes:
      - /bw-data:/data
    restart: unless-stopped
  minecraft:
    build: multiprovider-lazymc
    container_name: minecraft
    environment:
      - SERVER_PROVIDER=purpur
      - MC_VERSION=1.19.4
      - MC_RAM_MAX=4G
    volumes:
      - /minecraft_server:/data
    ports:
      - "25565:25565"
      - "25566:25566"
    stdin_open: true
    tty: true
    restart: unless-stopped
  ritmo:
    image: joaocostaifg/ritmo:latest
    environment:
      - RITMO_ENV=/run/secrets/ritmo_env
    secrets:
      - ritmo_env
    container_name: ritmo
    restart: unless-stopped

volumes:
  site_app_data:

secrets:
  ritmo_env:
    file: /usr/local/etc/ritmo_env
