services:
  php:
    build:
      context: ./src
      target: php_prod
    container_name: php
    ports:
      - "8000:8000"
      - "8001:9000"
    volumes:
      - site_app_data:/data
    restart: unless-stopped
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    environment:
      - langtool_languageModel=/ngrams
      - Java_Xms=256m  # minimum Java heap size of 256 mib
      - Java_Xmx=1g  # maximum Java heap size of 1 Gib
    ports:
      - "8010:8010"
    volumes:
      - /usr/local/lib/ngrams:/ngrams
    restart: unless-stopped
  vaultwarden:
    image: vaultwarden/server:1.30.5
    container_name: vaultwarden
    environment:
      - WEBSOCKET_ENABLED=true
    ports:
      - "8020:80"
      - "8021:3012"
    volumes:
      - site_bw_data:/data
    restart: unless-stopped
  wiki:
    image: ghcr.io/requarks/wiki:2.5
    container_name: wiki
    environment:
      - DB_TYPE=sqlite
      - DB_FILEPATH=/data/db.sqlite
    volumes:
      - site_wiki_data:/data
    ports:
      - "8030:3000"
    restart: unless-stopped
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - site_heimdall_data:/config
    ports:
      - 8040:80
    restart: unless-stopped
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    environment:
      - EULA=TRUE
      - TYPE=PURPUR
      - VERSION=1.19.4
      - MEMORY=6G
      - MAX_MEMORY=10G
      - USE_AIKAR_FLAGS=TRUE
      - USE_SIMD_FLAGS=TRUE
    volumes:
      - site_mine_data:/data
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true
    restart: unless-stopped
  pingvin-share:
    image: stonith404/pingvin-share
    container_name: pingvin
    ports:
      - 8050:3000
    volumes:
      - site_pingvin_data:/opt/app/backend/data
      - site_pingvin_imgs:/opt/app/frontend/public/img
    restart: unless-stopped
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: pdf
    ports:
      - '8060:8080'
    volumes:
      - site_pdf_trainingdata:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - site_pdf_config:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
    restart: unless-stopped
  couchdb_obsidian:
    build:
      context: couchdb_for_obsidian
    container_name: couchdb_obsidian
    ports:
      - "5984:5984"
    # need COUCHDB_USER AND COUCHDB_PASSWORD env vars
    env_file: "/usr/local/etc/couchdb.env"
    volumes:
      - obsidian_data:/opt/couchdb/data
      - obsidian_etc:/opt/couchdb/etc/local.d
    restart: unless-stopped
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "8100:8080"
    userns_mode: 'host'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
  shiori:
    image: ghcr.io/go-shiori/shiori
    container_name: shiori
    ports:
      - "8110:8080"
    volumes:
      - shiori_data:/shiori

volumes:
  site_app_data:
  site_bw_data:
  site_wiki_data:
  site_heimdall_data:
  site_mine_data:
  site_ritmo_data:
  site_pingvin_data:
  site_pingvin_imgs:
  site_pdf_trainingdata:
  site_pdf_config:
  shiori_data:
  obsidian_data:
  obsidian_etc:

secrets:
  ritmo_env:
    file: /usr/local/etc/ritmo_env
