services:
  tor:
    volumes:
      - /var/log:/var/log
      - tor_data:/var/lib/tor
  php:
    volumes:
      - /var/log:/var/log
      - app_code:/app
      - site_app_data:/data
  nginx:
    volumes:
      - /var/log:/var/log
      - :/etc/letsencrypt:ro
      - app_code:/app
      - site_app_data:/data

volumes:
  app_code:
  site_app_data:
    external: true
  tor_data:

secrets:
  joaocosta.dev:
    file: /etc/letsencrypt/joaocosta.dev
  joaocosta.dev_ecc:
    file: /etc/letsencrypt/joaocosta.dev_ecc
