services:
  tor:
    volumes:
      - tor_data:/var/lib/tor
  php:
    build:
      target: php_prod
    volumes:
      - app_code:/app
      - site_app_data:/data
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.prod
    volumes:
      - app_code:/app
      - site_app_data:/data

volumes:
  app_code:
  site_app_data:
    external: true
  tor_data:

secrets:
  joaocosta.dev:
    file: /etc/letsencrypt/joaocosta.dev
  joaocosta.dev_ecc:
    file: /etc/letsencrypt/joaocosta.dev_ecc
