services:
  tor:
    volumes:
      - tor_data:/var/lib/tor
  php:
    build:
      target: php_prod
    volumes:
      - app_code:/app
      - site_app_data:/data
  nginx:
    build:
      target: nginx_prod
    volumes:
      - app_code:/app
      - site_app_data:/data
      - /run/tailscale.nginx-auth.sock:/run/tailscale.nginx-auth.sock
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    networks:
      - languagetool_internal
    environment:
      - langtool_languageModel=/ngrams
    volumes:
      - /usr/local/lib/ngrams:/ngrams
    environment:
      - Java_Xms=256m  # minimum Java heap size of 256 mib
      - Java_Xmx=1g  # maximum Java heap size of 1 Gib
    restart: unless-stopped
  vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    networks:
      - vaultwarden_internal
    environment:
      - WEBSOCKET_ENABLED=true
    volumes:
      - /bw-data:/data
    restart: unless-stopped
  uptimekuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    networks:
      - uptimekuma_internal
    volumes:
      - /uptime-kuma:/app/data
      - /run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  minecraft:
    image: joaocostaifg/lazymc-purpur:1.19.3-lazymc0.2.7x64
    container_name: minecraft
    environment:
      - MC_RAM_MAX=4G
    volumes:
      - /minecraft_server:/data
    ports:
      - "25565:25565"
      - "25566:25566"
    restart: unless-stopped

volumes:
  app_code:
  site_app_data:
    external: true
  tor_data:

secrets:
  joaocosta.dev:
    file: /etc/letsencrypt/joaocosta.dev
  joaocosta.dev_ecc:
    file: /etc/letsencrypt/joaocosta.dev_ecc
