version: "3.9"

services:
  php:
    build:
      target: php_prod
    volumes:
      - site_app_data:/data
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool
    environment:
      - langtool_languageModel=/ngrams
      - Java_Xms=256m  # minimum Java heap size of 256 mib
      - Java_Xmx=1g  # maximum Java heap size of 1 Gib
    ports:
      - "8010:8010"
    volumes:
      - /usr/local/lib/ngrams:/ngrams
    restart: unless-stopped
  vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    environment:
      - WEBSOCKET_ENABLED=true
    ports:
      - "8020:80"
      - "8021:3012"
    volumes:
      - site_bw_data:/data
    restart: unless-stopped
  wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: wiki
    environment:
      - DB_TYPE=sqlite
      - DB_FILEPATH=/data/db.sqlite
    volumes:
      - site_wiki_data:/data
    ports:
      - "8030:3000"
    restart: unless-stopped
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - site_heimdall_data:/config
    ports:
      - 8040:80
    restart: unless-stopped
  minecraft:
    build:
      context: ./multiprovider-lazymc
      args:
        - SERVER_PROVIDER=purpur
        - MC_VERSION=1.19.4
    container_name: minecraft
    environment:
      - MC_RAM_MAX=4G
    volumes:
      - site_mine_data:/data
    ports:
      - "25565:25565"
      - "25566:25566"
    stdin_open: true
    tty: true
    restart: unless-stopped
  ritmo:
    image: joaocostaifg/ritmo:latest
    environment:
      - RITMO_ENV=/run/secrets/ritmo_env
    secrets:
      - ritmo_env
    container_name: ritmo
    restart: unless-stopped
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 8050:3000
    volumes:
      - site_pingvin_data:/opt/app/backend/data
      - site_pingvin_imgs:/opt/app/frontend/public/img

volumes:
  site_app_data:
  site_bw_data:
  site_wiki_data:
  site_heimdall_data:
  site_mine_data:
  site_pingvin_data:
  site_pingvin_imgs:

secrets:
  ritmo_env:
    file: /usr/local/etc/ritmo_env
