services:
  caddy:
    image: ghcr.io/joaocostaifg/caddy:master
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - /run/tailscale/tailscaled.sock:/run/tailscale/tailscaled.sock
    env_file: /usr/local/etc/caddy.env
    restart: unless-stopped
  # ---
  php:
    image: ghcr.io/joaocostaifg/website:master
    container_name: php
    environment:
      - ENV_PASSWORD_FILE=/run/secrets/site_env_password
    secrets:
      - site_env_password
    expose:
      - "8000"
      - "9000"
    volumes:
      - site_app_data:/data
    restart: unless-stopped
  # ---
  vaultwarden:
    image: vaultwarden/server:1.33.2
    container_name: vaultwarden
    environment:
      - WEBSOCKET_ENABLED=true
      - EXPERIMENTAL_CLIENT_FEATURE_FLAGS=ssh-key-vault-item,ssh-agent
    expose:
      - "80"
      - "3012"
    volumes:
      - site_bw_data:/data
    restart: unless-stopped
  # ---
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - site_heimdall_data:/config
    expose:
      - "80"
    restart: unless-stopped
  # ---
  minecraft:
    image: itzg/minecraft-server:java21-graalvm
    container_name: minecraft
    environment:
      - EULA=TRUE
      - TYPE=PURPUR
      - VERSION=1.19.4
      - MEMORY=6G
      - MAX_MEMORY=10G
      - USE_AIKAR_FLAGS=TRUE
      - USE_SIMD_FLAGS=TRUE
    volumes:
      - site_mine_data:/data
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true
    restart: unless-stopped
  # ---
  pingvin-share:
    image: stonith404/pingvin-share
    container_name: pingvin
    expose:
      - "3000"
    volumes:
      - site_pingvin_data:/opt/app/backend/data
      - site_pingvin_imgs:/opt/app/frontend/public/img
    restart: unless-stopped
  # ---
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: pdf
    expose:
      - "8080"
    volumes:
      - site_pdf_trainingdata:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - site_pdf_config:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
    restart: unless-stopped
  # ---
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    expose:
      - "8080"
    userns_mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
  # ---
  joplin:
    image: joplin/server:latest
    container_name: joplin
    expose:
      - "22300"
    environment:
      - APP_BASE_URL=https://joplin.joaocosta.dev
      - APP_PORT=22300
      - SQLITE_DATABASE=/data/db.sqlite
    volumes:
      - joplin_data:/data
    restart: unless-stopped
  # ---
  rss2email:
    image: ghcr.io/skx/rss2email:master
    container_name: rss2email
    working_dir: /app
    entrypoint: rss2email
    command: daemon -verbose rss@joaocosta.dev
    environment:
      - TZ=UTC
    env_file: /usr/local/etc/rss2email.env
    volumes:
      - rss2email-data:/app/.rss2email
    restart: unless-stopped
  # ---
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui_data:/app/backend/data
    expose:
      - "8080"
    restart: unless-stopped
  # --- paperless
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    depends_on:
      - paperless-broker
      - gotenberg
      - tika
    expose:
      - "8000"
    volumes:
      - paperless_data:/usr/src/paperless/data
      - paperless_media:/usr/src/paperless/media
      - /paperless/export:/usr/src/paperless/export
      - /paperless/consume:/usr/src/paperless/consume
    env_file: /usr/local/etc/paperless.env
    environment:
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    restart: unless-stopped
  paperless-broker:
    image: docker.io/library/redis:7
    expose:
      - "6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped
  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    expose:
      - "3000"
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    restart: unless-stopped
  tika:
    # - Apache Tika and Gotenberg servers are started with paperless and paperless
    #   is configured to use these services. These provide support for consuming
    #   Office documents (Word, Excel, Power Point and their LibreOffice counter-
    #   parts.
    image: docker.io/apache/tika:latest
    expose:
      - "9998"
    restart: unless-stopped

volumes:
  site_app_data:
  site_bw_data:
  site_wiki_data:
  site_heimdall_data:
  site_mine_data:
  site_pingvin_data:
  site_pingvin_imgs:
  site_pdf_trainingdata:
  site_pdf_config:
  joplin_data:
  rss2email-data:
  open-webui_data:
  caddy_data:
  caddy_config:
  # ---
  paperless_data:
  paperless_media:
  redisdata:

secrets:
  site_env_password:
    file: /usr/local/etc/site_env_password
