version: "3.3"

services:
  snikket_proxy:
    container_name: snikket-proxy
    image: snikket/snikket-web-proxy:stable
    env_file: snikket.conf
    userns_mode: 'host'
    network_mode: host
    volumes:
      - snikket_data:/snikket
      - snikket_acme_challenges:/var/www/html/.well-known/acme-challenge
    restart: "unless-stopped"
  snikket_certs:
    container_name: snikket-certs
    image: snikket/snikket-cert-manager:stable
    userns_mode: 'host'
    network_mode: host
    env_file: snikket.conf
    volumes:
      - snikket_data:/snikket
      - snikket_acme_challenges:/var/www/.well-known/acme-challenge
    restart: "unless-stopped"
    command: ["--", "/bin/bash", "-c", "/usr/bin/chown -R root:root /usr/bin && /entrypoint.sh"]
  snikket_portal:
    container_name: snikket-portal
    image: snikket/snikket-web-portal:stable
    userns_mode: 'host'
    network_mode: host
    env_file: snikket.conf
    restart: "unless-stopped"
  snikket_server:
    container_name: snikket
    image: snikket/snikket-server:stable
    userns_mode: 'host'
    network_mode: host
    volumes:
      - snikket_data:/snikket
    env_file: snikket.conf
    restart: "unless-stopped"

volumes:
  snikket_acme_challenges:
  snikket_data:
