version: "3"

server:
  command: "php ./vendor/bin/rr-worker start --relay-dsn unix:///var/run/rr-relay.sock"
  relay: "unix:///var/run/rr-relay.sock"

http:
  address: 0.0.0.0:8000
  middleware: ["static"]
  pool:
    max_jobs: 64
    supervisor:
      exec_ttl: 60s
  static:
    dir: "public"
    forbid: [".php"]

logs:
  encoding: json
  level: error
  mode: production
