---
- name: joaocosta.dev nginx VM (ifgsv) Ansible playbook (update)
  hosts: joaocostadev_nginx
  become: no
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 86400
