---
- name: Update packages and cache
  community.general.pacman:
    update_cache: yes
    upgrade: yes
- name: Install base dependencies
  community.general.pacman:
    name:
      - cpupower
      - cronie
      - git
      - intel-ucode
      - neofetch
      - neovim
      - pacman-contrib
      - reflector
      - rsync
    state: present
- name: Setup reflector
  copy:
    src: reflector.conf
    dest: /etc/xdg/reflector/reflector.conf
  notify: restart reflector
- name: Enable cpupower systemd timer
  systemd:
    name: reflector.timer
    enabled: yes
    masked: no
- name: Setup cpupower config
  copy:
    src: cpupower
    dest: /etc/default/cpupower
  notify: restart cpupower
- name: Enable cpupower systemd service
  systemd:
    name: cpupower
    enabled: yes
    masked: no
