---
- name: Install docker and docker-compose
  community.general.apk:
    name:
      - docker
      - docker-cli-compose
    update_cache: true
    state: present
- name: Enable ntpd service
  ansible.builtin.service:
    name: ntpd
    enabled: true
    state: started
- name: Enable docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
- name: Set docker daemon options
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: restart docker
