---
- name: Fetch site files
  ansible.builtin.git:
    repo: "https://github.com/JoaoCostaIFG/website.git"
    dest: /root/website
    version:  "{{ repo_branch }}"
  environment:
    GIT_TERMINAL_PROMPT: 0 # reports "terminal prompts disabled" on missing password
  #notify: restart services
- name: (re)start services
  command:
    chdir: /root/website/site
    cmd: docker compose -f production.yml -f snikket.yml up --build -d
