---
- name: Install npm
  community.general.apk:
    name:
      - nodejs
      - nodejs-npm
    update_cache: true
    state: present
- block:
  - name: Fetch site files
    ansible.builtin.git:
      repo: "https://github.com/JoaoCostaIFG/website.git"
      dest: /usr/local/src/website
    environment:
      GIT_TERMINAL_PROMPT: 0 # reports "terminal prompts disabled" on missing password
  - name: Build fontawesome font
    ansible.builtin.shell: npm i -D && npm run build
    args:
      chdir: /usr/local/src/website/site/fontawesome_subsetter
  notify: restart services
