---
- name: Install docker and docker-compose
  community.general.pacman:
    name:
      - docker
      - docker-buildx
      - docker-compose
    state: present
  notify: restart docker
- name: Enable docker socket systemd service
  systemd:
    name: docker
    enabled: yes
    masked: no
- name: Change default log-driver to `local`
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
