FROM alpine:3.14 as builder

RUN apk --no-cache add composer
# wiki code
COPY wiki /app/wiki
# site code
COPY src /app/main
# composer
RUN cd /app/main && composer install -n -o

FROM nginx:alpine

# nginx conf
COPY nginx/nginx-conf /etc/nginx

COPY --from=builder /app /app

EXPOSE 80 443
