---
- name: Install tailscale daemon
  ansible.builtin.apt:
    name:
      - tailscale
      - tailscale-nginx-auth
    state: present
  notify:
    - restart tailscaled
    - restart tailscale.nginx-auth
- name: Enable tailscale daemon systemd service
  systemd:
    name: tailscaled
    enabled: yes
    masked: no
- name: Enable tailscale.nginx-auth daemon systemd service
  systemd:
    name: tailscale.nginx-auth
    enabled: yes
    masked: no
