---
- name: Install cloudflare DDNS daemon python dependencies
  ansible.builtin.apt:
    name:
      - python3-cloudflare
      - python3-requests
      - git
      - make
    state: present
- name: Fetch cloudflare DDNS source files
  ansible.builtin.git:
    repo: "https://github.com/JoaoCostaIFG/cloudflareddns.git"
    dest: /usr/local/src/cloudflareddns
    version: "{{ cfddns_version }}"
  environment:
    GIT_TERMINAL_PROMPT: 0 # reports "terminal prompts disabled" on missing password
  notify: install cfddns
- name: Configure cloudflare DDNS
  template:
    src: cfddns-config.json.j2
    dest: /usr/local/etc/cfddns-config.json
    owner: root
    group: root
    mode: '0600'
  no_log: True
- name: Schedule DDNS update with cron
  ansible.builtin.cron:
    name: "DDNS"
    minute: "*/10"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "CFDDNS_CONFIG=/usr/local/etc/cfddns-config.json /usr/local/bin/cfddns.py"
