---
- name: Config apt sources
  ansible.builtin.copy:
    src: sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
- name: Config kernel params
  ansible.builtin.copy:
    src: cmdline
    dest: /etc/kernel/cmdline
    owner: root
    group: root
    mode: '0644'
- name: Update systemd-boot params
  ansible.builtin.command:
    cmd: /usr/sbin/proxmox-boot-tool refresh
