name: Get Blog contents from Joplin

on:
  workflow_dispatch:

env:
  NOTEBOOK_NAME: Blog
  OUTPUT_DIR: joaocosta.dev

permissions:
  contents: write
  id-token: write

concurrency:
  group: "joplin"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # cache: "npm"
          # cache-dependency-path: joplin_exporter/package-lock.json
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Login and sync Joplin Wiki notebook
        env:
          JOPLIN_PATH: ${{ secrets.JOPLIN_PATH }}
          JOPLIN_USER: ${{ secrets.JOPLIN_USER }}
          JOPLIN_PASSWORD: ${{ secrets.JOPLIN_PASSWORD }}
        run: |
          npm i joplin
          tmp="$(mktemp -d)"
          joplin_exporter/export_joplin.sh "${{ env.NOTEBOOK_NAME }}" "$tmp"
          rm -rf "${{ env.OUTPUT_DIR }}/posts" "${{ env.OUTPUT_DIR }}/public/_resources"
          mv "$tmp/${{ env.NOTEBOOK_NAME }}" "${{ env.OUTPUT_DIR }}/posts"
          mv "$tmp/_resources" "${{ env.OUTPUT_DIR }}/public/_resources"
          rm -rf "$tmp"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          # Check if there are any changes in the output directory
          if ! git diff --quiet --exit-code "${{ env.OUTPUT_DIR }}"; then
            echo "Changes detected in ${{ env.OUTPUT_DIR }}. Committing..."
            git add ${{ env.OUTPUT_DIR }}
            git commit -m "Update Joplin export: ${{ env.NOTEBOOK_NAME }} ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push
          else
            echo "No changes to commit in ${{ env.OUTPUT_DIR }}."
          fi
