---
- name: restart tailscaled
  systemd:
    name: tailscaled
    state: restarted
    daemon_reload: no
- name: restart tailscale.nginx-auth
  systemd:
    name: tailscale.nginx-auth
    state: restarted
    daemon_reload: no
